export interface GTProjectSection {
  heading: string;
  content: string;
}

export interface GTProject {
  slug: string;
  title: string;
  course: string;
  institution: string;
  period: string;
  description: string;
  tags: string[];
  metrics?: string[];
  sections: GTProjectSection[];
}

export const gtProjects: GTProject[] = [
  {
    slug: "ml4t-trading-strategy",
    title: "Algorithmic Trading Strategy System",
    course: "CS 7646:Machine Learning for Trading",
    institution: "Georgia Tech",
    period: "Fall 2025",
    description:
      "\nCapstone project building two trading systems for JPM. A manual rule-based strategy and an ML strategy learner using the same four technical indicators. Both evaluated in and out of sample against a buy and hold benchmark.",
    tags: ["Python", "NumPy", "Pandas", "Machine Learning","Random Forest", "Technical Analysis"],
    metrics: ["Learner: +30.8% in sample", "Learner: +8.2%  out of sample", "Benchmark: −8.4%  out of sample"],
    sections: [
      {
        heading: "Overview",
        content: `The final project in CS 7646 is a head to head comparison between two trading strategies: one built by hand using domain knowledge and rules, the other learned by a machine from historical data. Both trade JPM stock starting with $100,000. The in sample training period runs from January 2008 to December 2009. The  out of sample evaluation period runs from January 2010 to December 2011 that neither strategy was allowed to see during development.

The benchmark in both cases is a simple buy and hold: buy 1,000 shares on the first trading day and hold. The goal is to beat it, particularly  out of sample where overfitting is exposed.`,
      },
      {
        heading: "Indicators",
        content: `Both strategies use the same four technical indicators. Using the same signal inputs lets the comparison isolate how much the decision logic matters, rather than what information was available.

Bollinger %B (BBP) measures where price sits within its 20 day Bollinger Band. A value near 0 means price is at the lower band (historically oversold); near 1 means it is at the upper band (historically overbought). RSI is a 14 period Relative Strength Index calculated with exponential weighting. Values below 40 indicate oversold conditions; above 60 indicate overbought.

Momentum measures how much price has moved over the past 10 days, expressed as a ratio. It captures direction and magnitude of recent price movement without smoothing. EMA Distance measures how far price has stretched from its 20 period exponential moving average, normalized as a percentage. When price is significantly above its EMA it tends to mean revert; when below, the opposite.`,
      },
      {
        heading: "Manual Strategy",
        content: `The manual strategy uses a three indicator confirmation rule for entries. A long position is entered when RSI falls below 40, BBP falls below 0.3, and Momentum is negative. A short position is entered when RSI rises above 60, BBP rises above 0.8, and Momentum is positive. Requiring agreement across multiple indicators reduces false signals at the cost of fewer total trades.

Exit logic is simpler. A long position is closed when RSI rises above 55, indicating the oversold condition has resolved. A short position is closed when RSI falls below 45 or EMA Distance turns negative, suggesting the overbought condition has reversed or price has dropped back below its trend. The EMA Distance condition on short exits adds a momentum based escape valve for sudden reversals.

in sample the strategy returned +15.6% against a benchmark of +1.2%. The manual rules were developed exclusively on in sample data and the  out of sample period was never examined during development.  out of sample the strategy returned -5.9%, compared to the benchmark's -8.4%. The rules didn't generate positive returns in the 2010–2011 period, but they still beat passive holding.`,
      },
      {
        heading: "Strategy Learner",
        content: `The strategy learner frames trading as a classification problem. The same four indicators plus raw price are used as input features. For each day in the training set, a label is generated by looking N=5 trading days forward: if the return exceeds +1% plus the market impact cost, the label is LONG; if it drops below -1% minus impact, the label is SHORT; otherwise it is CASH.

The impact sensitive threshold is the key design decision. Higher market impact raises the return needed to justify a trade, so the learner naturally reduces trade frequency as costs rise. This makes the model aware of transaction economics during training rather than only during execution.

The classifier is a Random Forest: a BagLearner of 20 RTLearners (a Random Tree variant), each built with a minimum leaf size of 5 to prevent degenerate overfitting on the roughly 500 in sample data points. Training calls add_evidence() and freezes the model. Inference calls testPolicy() using the same features on the new time period, with no retraining.

The learner returned +30.8% in sample, roughly double the manual strategy, and +8.2%  out of sample. The benchmark returned -8.4% in the same  out of sample period, meaning the learner generated positive returns in a period where passive holding lost money.`,
      },
      {
        heading: "ML Implementation",
        content: `The feature matrix has five columns: raw price, Momentum, RSI, Bollinger %B, and EMA Distance. No external normalization is applied. RTLearner splits on raw feature values, so the scale of each indicator relative to itself is what matters, not interfeature comparability. Missing values from indicator lookback warm up periods are filled with zero before training. The last N rows of each training window are dropped because they cannot have valid forward looking labels.

The RTLearner is a Random Tree, or a variation on a standard decision tree that selects both the split feature and the split value randomly (uniform draw from the feature's observed range) rather than searching for the optimal split. This makes each tree faster to build and less correlated with its siblings, which is exactly what bagging needs to work. Each tree grows until leaf nodes contain five or fewer samples, preventing the degenerate case where individual trees memorize the roughly 500 training points.

The BagLearner wraps 20 RTLearners. Each bag trains on a bootstrap sample so each tree sees a different slice of the data. At inference time all 20 trees produce a prediction and the mean of their outputs determines the signal: positive means LONG, negative means SHORT, nearzero means CASH. Averaging across decorrelated trees substantially reduces variance compared to any single tree. The model is fully frozen after add_evidence() returns; testPolicy() only calls query() with no weight updates.`,
      },
      {
        heading: "Experiments",
        content: `Experiment 1 was a direct three way comparison between the Manual Strategy, Strategy Learner, and Benchmark. The learner outperformed the manual strategy in sample (+30.8% vs +15.6%) and was the only strategy to generate positive returns  out of sample (+8.2%), while both the manual strategy (-5.9%) and the benchmark (-8.4%) lost money. The manual strategy's in sample edge didn't transfer cleanly to new data, a typical symptom of hand tuned rules that capture historical noise rather than durable patterns. The learner generalized better because it found signal combinations the rules missed.

Experiment 2 tested whether the impact sensitive label design actually changed trading behavior. The learner was trained and evaluated four times on the in sample period with impact values of 0.0, 0.005, 0.01, and 0.02, with commission fixed at $0 to isolate impact as the only cost variable.

The mechanism is straightforward: at impact=0.0 the LONG and SHORT thresholds are ±1%, so any day with a projected 5 day return beyond those bounds gets labeled as a signal. At impact=0.02 those thresholds widen to +3% and -3%. Far fewer days in the training set clear that bar, so the model learns a more conservative policy with fewer, higher conviction entries. The results confirmed this monotonically: trade count fell and cumulative return declined as impact rose. The important result isn't the return degradation as that's expected when costs rise. It's that the behavior change came from the label construction during training, not from a post hoc filter applied at inference time.`,
      },
    ],
  },
  {
    slug: "enron-fraud-detection",
    title: "Enron Email Fraud Detection Pipeline",
    course: "INTA 6450:Data Analysis",
    institution: "Georgia Tech",
    period: "Spring 2026",
    description:
      "Group project analyzing 500,000 Enron emails for evidence of market manipulation during the California energy crisis. Four phase pipeline: network graph analysis, temporal filtering, custom NLP lexicons, and composite risk scoring.",
    tags: ["Python", "NetworkX", "NLP", "VADER", "Pandas", "NumPy", "Regex"],
    metrics: ["500K emails processed", "4 phase cascading funnel", "18 convicted individuals"],
    sections: [
      {
        heading: "Overview",
        content: `The Enron scandal is one of the most well documented cases of corporate fraud in American history. When Enron collapsed in 2001, investigators released roughly 500,000 internal emails that have since become a standard research dataset. The challenge is not finding the corpus, it is making sense of it. The vast majority of emails are routine: scheduling, HR, forwarded news articles, and meeting logistics. The wrongdoing is buried inside operational communications that look, on the surface, like normal trading desk activity.

This project was a group effort with three classmates for INTA 6450 at Georgia Tech. The goal was to build a pipeline that could take the entire raw corpus and deterministically surface the emails most likely to contain evidence of constructive fraud. We focused specifically on the market manipulation Enron's West Power Trading Desk ran during California's 2000 to 2001 energy crisis. The wrongdoing we targeted was the "Ricochet" scheme: purchasing price capped California power, exporting it to Oregon or Nevada, and reimporting it back into California as "out of state" power exempt from price caps. That arbitrage left a very specific communication trail between schedulers and traders, which gave us a behavioral fingerprint to search for.`,
      },
      {
        heading: "Phase 1: Network and Actor Filtering",
        content: `The first phase builds a directed communication graph from every email header in the corpus using NetworkX. Each unique email address is a node; each sent message creates a directed edge. With 500,000 emails that produces a graph with tens of thousands of nodes, so we used sampled betweenness centrality (k=200 nodes) to identify which addresses served as bridges in the communication network without waiting hours for an exact computation.

We focused on the West Power Trading Desk because that is where the California manipulation was operationally coordinated. Before running the graph analysis we hand mapped every known email alias for 15 West Desk actors from FERC dockets and DOJ plea records. Tim Belden alone had four different email addresses in the corpus. Without that alias resolution, the graph would treat each variant as a separate node and undercount their centrality.

The top 15 West Desk actors by centrality became the seeds of an ego network: every node they sent to or received from was pulled into Phase 1. We also injected the full list of 18 convicted individuals as mandatory includes. That filter reduced 500,000 emails to roughly 165,000.`,
      },
      {
        heading: "Phase 2: Temporal Masking",
        content: `Phase 2 restricts the dataset to emails sent within 48 hours of a known CAISO Stage 3 emergency or rolling blackout. Those 16 dates span June 2000 through June 2001 and were sourced from FERC reports on the crisis. The reasoning is straightforward: if traders were actively coordinating market manipulation during grid emergencies, the email traffic around those events is where that coordination would appear.

We implemented this using NumPy broadcasting rather than looping over each email. The array of email timestamps and the array of 16 crisis dates are broadcast against each other to compute a full distance matrix in one operation, then we take the row wise minimum to get each email's proximity to the nearest crisis. Anything within 48 hours passes. This ran on the 165,000 Phase 1 emails in seconds and reduced the corpus to about 11,000.`,
      },
      {
        heading: "Phase 3: Linguistic Feature Extraction",
        content: `Phase 3 scores every remaining email against three custom lexicons we built by researching the specific language Enron traders used internally and in FERC investigation records.

The gaming lexicon (55 terms) targets manipulation specific vocabulary: "Death Star", "Fat Boy", "Ricochet", "megawatt laundering", "round trip", "wash trade". These terms were coined internally by the trading desk and have no legitimate use in normal grid operations. The hedging lexicon (48 terms) looks for distancing and uncertainty language: "probably", "should appear", "we think", "it seems". That pattern of deliberate vagueness tends to appear in emails where someone is trying to create deniability. The optics lexicon (55 terms) targets impression management phrases: "make the numbers work", "keep this quiet", "avoid the optics", "off the record".

On top of the lexicons we ran VADER sentiment analysis on the original authored text of each email, not the quoted chains. The flag we care about is anomalously positive sentiment during a blackout. Normal grid professionals treat rolling blackouts as failures. Enron traders viewed them as profit opportunities, so celebration language near crisis dates is a behavioral signal.

Each email also gets scored against sets of California operations terms, suspicious mechanics terms, transaction terms, and concealment terms. The combination of signals determines whether an email passes a hard gate into Phase 4 or gets filtered out. We also built explicit exclusion logic for news digests, forwarded announcements, regulatory summaries, and deal confirmation workflow, all of which generate false positives if you just count lexicon hits without context.`,
      },
      {
        heading: "Composite Risk Scoring",
        content: `Phase 4 produces a 0 to 1 composite risk score for each surviving email using a weighted linear combination of the normalized Phase 3 signals. The base formula weighted gaming highest at 35%, temporal proximity at 20%, optics at 15%, hedging at 15%, and sentiment anomaly at 10%. We also applied an actor boost for emails involving West Desk members or convicted individuals, and an interaction boost for emails where gaming, California operations, and transaction signals all fired simultaneously.

We also used logistic regression to validate and calibrate the core weights. The model was fit on the Phase 2 emails with convicted person involvement as the binary label. The resulting coefficient magnitudes gave us a data driven check on our manual weights, and in most runs they agreed closely with the hand tuned values.

Evidence tier classification ran separately from the score. An email could be tagged "direct" (contains a smoking gun term or the combination of strong gaming plus suspicious mechanics), "supporting" (California operations plus transaction activity plus concealment or actor involvement), or "none". The tier did not change the numeric ranking but gave reviewers a way to understand why an email scored high.`,
      },
      {
        heading: "Results and Findings",
        content: `The pipeline narrowed 500,000 raw emails to 50 highest risk operational communications. The funnel: 500K raw, 249K after deduplication (the corpus stores each email in every recipient's mailbox, so a 10 person thread produces 10 copies), 165K after Phase 1, 11K after Phase 2, and then the final scoring ranked those down to the top 50.

The most interesting finding was that none of the top 5 ranked emails came from a convicted individual as the sender, though several were sent to them. Our analysis suggests two reasons. Convicted executives were careful about committing plans to writing, so the operational instructions often traveled through subordinates or were given verbally. The people who actually sent emails discussing the mechanics were the schedulers and desk traders carrying out the trades, not the executives who designed the schemes. The pipeline surfaced that layer of the organization rather than the executives everyone already knew about.

Lexicon rate comparisons confirmed the model was discriminating correctly: emails involving convicted individuals showed significantly higher rates of gaming, hedging, and optics hits than the general Phase 2 population. But those convicted individuals were not the top ranked senders by mean risk score. That list was entirely non convicted employees whose emails showed direct operational coordination language around crisis dates.

The paper also identified several areas for future improvement: replacing the static lexicons with a feedback loop that dynamically expands vocabulary based on high scoring results, replacing linear weights with an exponential or logarithmic cost function for sharper differentiation, and building a labeled training set to move weight optimization from manual heuristics to supervised learning.`,
      },
    ],
  },
  {
    slug: "ai-expectation-maximization",
    title: "Image Segmentation with Expectation Maximization",
    course: "CS 6601: Artificial Intelligence",
    institution: "Georgia Tech",
    period: "Spring 2026",
    description:
      "Implemented k-means and a full multivariate Gaussian Mixture Model with expectation maximization from scratch in NumPy. Applied to Van Gogh's Starry Night and 3D point cloud segmentation. Vectorized E step runs in 37ms, the loop equivalent takes hours.",
    tags: ["Python", "NumPy", "Unsupervised Learning", "EM Algorithm", "Gaussian Mixture Models", "Image Processing"],
    metrics: ["Full EM from scratch", "Starry Night + 3D point cloud", "Vectorized: 37ms per E step"],
    sections: [
      {
        heading: "Overview",
        content: `The assignment covers unsupervised learning through image segmentation in CS 6601 at Georgia Tech. The goal is to take a raw RGB image, group its pixels into k color clusters, and return a compressed version where every pixel is replaced by the mean color of its assigned component. The same algorithms run on 3D point cloud data to segment objects by spatial region.

There are five graded parts: a k-means baseline, a full multivariate Gaussian Mixture Model, two model improvements, and a Bayesian Information Criterion implementation for automatic component selection. All code had to run within 10 minutes on the autograder. A naive loop over each pixel takes hours on a full resolution image. Full NumPy vectorization was required across every core function.`,
      },
      {
        heading: "k-means Baseline",
        content: `k-means is the starting point. The implementation has three functions: get_initial_means() draws k random pixel values as starting centroids without replacement, k_means_step() assigns every pixel to its nearest centroid and recomputes cluster means, and k_means_segment() iterates k_means_step() until cluster assignments stop changing, then replaces each pixel's RGB values with its centroid color.

The vectorized distance computation in k_means_step() is the key performance decision. The expression X[:, None, :] - means[None, :, :] creates a broadcast difference of shape (m, k, 3), and np.linalg.norm(..., axis=2) collapses the color channels to produce an (m, k) distance matrix in one operation. np.argmin on that matrix gives cluster assignments for all m pixels simultaneously. Without this the 10 minute autograder limit is not achievable. The benchmarked runtime for k_means_segment on the Starry Night image is roughly 6.5 seconds.`,
      },
      {
        heading: "Gaussian Mixture Model",
        content: `A Gaussian Mixture Model represents the image as a weighted sum of k multivariate Gaussians, each defined by a mean vector (MU), a covariance matrix (SIGMA), and a mixing coefficient (PI). Rather than hard assigning each pixel to exactly one cluster, the GMM assigns each pixel a soft responsibility score for every component. The component with the highest responsibility determines the pixel's final segment.

The model has four parameter arrays: k component means of shape (k x 3) for RGB, k covariance matrices of shape (k x 3 x 3), k mixing coefficients summing to 1, and a responsibility matrix of shape (k x m) tracking each pixel's affinity for each component.

Initialization sets each component mean to a randomly sampled pixel, computes the initial covariances from those means using compute_sigma(), and sets mixing coefficients to a uniform 1/k. compute_sigma() is implemented as a loop over k components, each using the closed form outer product formula: the covariance for component i is (X - MU[i]).T @ (X - MU[i]) / m.`,
      },
      {
        heading: "EM Implementation",
        content: `The EM algorithm alternates between two steps until convergence.

The E step computes the responsibility of each Gaussian component for each pixel. For component i and pixel j, the responsibility is PI[i] times N(x_j; MU[i], SIGMA[i]), normalized across all components so responsibilities sum to 1 per pixel. N() is the multivariate Gaussian probability density function. The exponent is computed as 0.5 times the sum of (difference @ inv_sigma) * difference along the feature axis, which avoids materializing the full (m x m) intermediate matrix that naive matrix multiplication would produce. This is the most numerically sensitive part of the implementation: a shape mismatch here causes the autograder to allocate over 100 GiB and crash.

The M step re-estimates all parameters from the updated responsibilities. The new mean for component i is the responsibility weighted average of all pixels. The new covariance is the responsibility weighted outer product of pixel deviations from the updated mean. The new mixing coefficient is the sum of responsibilities for component i divided by total pixels. All three updates are closed form with no gradient descent. One full training run typically requires 15 to 20 iterations and converges in under 30 seconds with vectorization.

Log likelihood is computed as the sum over all pixels of the log of the total weighted probability under the model. The convergence condition fires when the new log likelihood is within 10% of the previous value for 10 consecutive iterations.`,
      },
      {
        heading: "Improved Initialization and Convergence",
        content: `The baseline GMM uses random initialization: k pixels are drawn at random as starting means. This works but is sensitive to bad draws where two initial means land in the same color region and a third is never assigned enough pixels to represent a real cluster.

The improved initialization uses one step of k-means to seed the Gaussian means instead. k-means tends to spread the initial means across distinct color regions because it iteratively pushes centroids apart. After k-means produces the means, compute_sigma() recalculates the covariances from scratch and mixing coefficients reset to uniform. The reset is intentional: GMMs tend to converge to elongated covariances during early training, and resetting those parameters before full EM begins reduces the chance of landing in a poor local maximum.

The new convergence function checks all three parameter sets instead of just the log likelihood. If all values in MU, SIGMA, and PI stay within 10% of their previous iteration values for 10 consecutive iterations, training stops. This catches cases where the likelihood plateaus but individual parameters are still drifting, which the default check would miss.`,
      },
      {
        heading: "BIC and Point Cloud Segmentation",
        content: `The Bayesian Information Criterion penalizes model complexity to prevent overfitting on the number of components. A GMM with k=20 will always fit the data better than one with k=3, but the extra components may be modeling noise rather than real color structure. BIC adds a penalty proportional to the number of free parameters times the log of the number of data points.

For a GMM with k components on 3 dimensional RGB data, the free parameters are the means (k times 3), the covariance entries (k times 9, since each covariance matrix is 3x3), and the mixing coefficients (k minus 1, since they sum to 1). The full formula is: BIC = number_of_parameters times ln(m) minus 2 times log_likelihood. Lower BIC is better. The implementation runs training for several values of k, computes BIC for each, and selects the k with the lowest score.

The final section extends the pipeline to 3D point cloud data. XYZ spatial coordinates replace RGB color values, and the same GMM and EM code runs without modification. Points that are spatially proximate cluster together, producing segmented objects and backgrounds from raw depth sensor output. The visual output is a point cloud where each segment is rendered in a distinct color, showing the algorithm generalizing cleanly from 2D image compression to 3D spatial partitioning.`,
      },
    ],
  },
];
